### PR TITLE
Update references and adding Russian Language

### PR DESCRIPTION
**Pull request by Kibnet**

### CODE REVIEW

**Comment by EchterAgo** [comment]
Hey, first thank you for this :) I think it would be better to direct this
pull to upstream first. Though if you want I can do the work of integrating
it too.

**Comment by EchterAgo** [comment]
Upstream wants more separated pull requests generally

**Comment by Kibnet** [comment]
This is my first pull request. Do whatever you want. I just want to improve this project.

**Comment by EchterAgo** [comment]
Ok, I've submitted this upstream:

https://github.com/tgjones/gemini/pull/225
https://github.com/tgjones/gemini/pull/226
https://github.com/tgjones/gemini/pull/227
https://github.com/tgjones/gemini/pull/228

Although I don't get why your fix for System.Windows.Interactivity.dll is needed. I've been using the new version of Mahapps.Metry for a long time in my internal branch and had no issues with it.

**Comment by EchterAgo** [comment]
If you can, please check the pull requests I've made. I did test them and they look to be working for me.

**Pull request closed without merging**
